pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'ls -al **/*.war'
                deploy war: '**/*.war', 
                  contextPath: '/', 
                  url: 'http://35.170.192.194:9090/'
            }
         }
    }
}
